name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      run: sudo apt-get install g++
      
    - name: Compile and run C++ programs
      run: |
        cd Cplusplus
        g++ -o program1 program1.cpp
        g++ -o program2 program2.cpp
        # Add more compilation and execution steps for other programs
        
    - name: Test C++ programs
      run: |
        cd Cplusplus
        ./program1
        ./program2
        # Add more test commands for other programs
