name: Go Programs Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20' # Specify your desired Go version
        
    - name: Run Go Programs
      run: |
        cd Golang
        for file in *.go; do
          echo "Checking $file..."
          go run "$file"
          if [ $? -eq 0 ]; then
            echo "$file is working."
          else
            echo "Error: $file is not working."
            exit 1
          fi
        done
