name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Check Python files in Python folder
      run: |
        find Python -type f -name "*.py" | while read -r file; do
          echo "Checking $file..."
          python "$file"
          if [ $? -eq 0 ]; then
            echo "$file is working."
          else
            echo "Error: $file is not working."
            exit 1
          fi
        done
